---
- name: Create nginx directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/nginx-proxy-manager/{{ item }}/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "data"
    - "letsencrypt"


- name: Create nginx proxy manager container
  community.docker.docker_container:
    name: nginx-proxy-manager
    image: docker.io/jc21/nginx-proxy-manager:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: wg_network
        ipv4_address: "{{ wg_nginx_ip }}"
      - name: dashy_network
        ipv4_address: "{{ dashy_nginx_ip }}"
      - name: pihole_network
        ipv4_address: "{{ pihole_nginx_ip }}"
    ports:
      - "{{ nginx_admin_port }}:81"
      - "{{ nginx_https_port }}:443"
    volumes:
      - "{{ docker_dir }}/nginx-proxy-manager/data:/data:z"
      - "{{ docker_dir }}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt:z"
