---
- name: Create dashy directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/dashy/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Create dashy config file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/dashy_conf.j2"
    dest: "{{ docker_dir }}/dashy/conf.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Dashy docker Container
  community.docker.docker_container:
    name: "dashy"
    image: docker.io/lissy93/dashy:latest
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "homelab_network"
        ipv4_address: "{{ dashy_ip }}"
    volumes:
      - "{{ docker_dir }}/dashy/conf.yml:/app/public/conf.yml:rw,z"
