---
- name: Update and install essential packages.
  become: true
  when: ansible_os_family == 'RedHat'
  block:
    - name: Update packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true
        update_cache: true

    - name: Remove unneeded packages
      ansible.builtin.dnf:
        autoremove: true

    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
      register: yum_install_status


- name: Reboot when packages were updated
  become: true
  ansible.builtin.reboot:
  when: yum_install_status.changed and ansible_os_family == "RedHat"

- name: Set Selinux to permissive
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/selinux.yml"
  when: ansible_os_family == 'RedHat'

- name: Install docker
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/docker.yml"
