- name: Update DNF based system
  block:
    - name: Update all installed packages using dnf module
      dnf:
        name: '*'
        state: latest
        update_cache: yes
        update_only: yes
      register: yum_update_status

    - name: Remove unneeded packages
      dnf:
        autoremove: yes

    - name: Reboot when packages were updated
      reboot:
      when: yum_update_status.changed
  when: ansible_os_family == "RedHat"

- name: Update APT based system
  block:
    - name: Update all installed packages using apt module
      apt:
        name: '*'
        state: latest
        update_cache: yes
        only_upgrade: yes
      register: apt_update_status

    - name: Remove unneeded packages
      apt:
        autoremove: yes

    - name: Reboot when packages were updated
      reboot:
        post_reboot_delay: 60
      when: apt_update_status.changed
  when: ansible_os_family == "Debian"

