---
- name: Create wg directory
  ansible.builtin.file:
    path: "{{ podman_dir }}/wg/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Modprobe iptable_raw and wireguard modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    persistent: present
  loop:
    - wireguard
    - iptable_raw

- name: Create wg container
  containers.podman.podman_container:
    name: wg
    image: docker.io/weejewel/wg-easy
    sysctl:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    state: started
    env:
      "PASSWORD": "{{ wg_password }}"
      "WG_HOST": "{{ ip_address }}"
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    volumes:
      - "{{ podman_dir }}/wg/:/etc/wireguard:z"
    restart_policy: unless-stopped
