---
username: user

podman_dir: /home/{{ username }}/podman

ip_address: hostname

wg_password: changeme

packages:
  - epel-release
  - unzip
  - wget
  - curl
  - git
  - vim
  - python3
  - python3-pip

podman_packages:
  - podman
  - podman-compose

