####  Rocky Packages  ####
packages:
  - epel-release
  - unzip
  - wget
  - curl
  - git
  - vim
  - python3
  - python3-pip
  - python3-requests

#### Rocky Podman pkgs ####
podman_packages:
  - podman
  - podman-compose


#### SeLinux policies ####
selinux_policy: targeted
selinux_state: permissive
