---
- name: Create pihole directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/pihole/{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
  loop:
    - "etc_pihole-unbound"
    - "etc_pihole_dnsmasq-unbound"

- name: Create unbound config file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/custom.list.j2"
    dest: "{{ docker_dir }}/pihole/etc_pihole-unbound/custom.list"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Create cname config file
  ansible.builtin.template:
    src: "{{ role_path }}/templates/05-pihole-custom-cname.conf.j2"
    dest: "{{ docker_dir }}/pihole/etc_pihole_dnsmasq-unbound/05-pihole-custom-cname.conf"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644

- name: Set up pihole service
  block:
    - name: Create pihole_unbound container
      community.docker.docker_container:
        name: pihole
        image: docker.io/cbcrowe/pihole-unbound:latest
        state: started
        restart_policy: unless-stopped
        hostname: "{{ pihole_hostname }}"
        networks:
          - name: homelab_network
            ipv4_address: "{{ pihole_ip }}"
        ports:
          - "{{ pihole_ftlconf_local_ipv4 }}:53:53/tcp"
          - "{{ pihole_ftlconf_local_ipv4 }}:53:53/udp"
          - 5335:5335/tcp
        env:
          FTLCONF_LOCAL_IPV4: "{{ pihole_ftlconf_local_ipv4 }}"
          TZ: "{{ pihole_tz }}"
          WEBPASSWORD: "{{ pihole_webpassword }}"
          WEBTHEME: "{{ pihole_webtheme }}"
          REV_SERVER: "{{ pihole_rev_server }}"
          REV_SERVER_TARGET: "{{ pihole_rev_server_target }}"
          REV_SERVER_DOMAIN: "{{ pihole_rev_server_domain }}"
          REV_SERVER_CIDR: "{{ pihole_rev_server_cidr }}"
          PIHOLE_DNS_: "127.0.0.1#5335"
          DNSSEC: "true"
          DNSMASQ_LISTENING: "single"
        volumes:
          - "{{ docker_dir }}/pihole/etc_pihole-unbound:/etc/pihole:rw,z"
          - "{{ docker_dir }}/pihole/etc_pihole_dnsmasq-unbound:/etc/dnsmasq.d:rw,z"
