---
- name: Create wg directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/wg/"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Modprobe iptable_raw and wireguard modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
    #persistent: present
  loop:
    - wireguard
    - iptable_raw

- name: Create wg container
  community.docker.docker_container:
    name: wg
    image: docker.io/weejewel/wg-easy:latest
    networks:
      - name: wg_network
        ipv4_address: "{{ wg_ip }}"
    sysctls:
      "net.ipv4.ip_forward": "1"
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    state: started
    env:
      "PASSWORD": "{{ wg_password }}"
      "WG_HOST": "{{ wg_ip_address }}"
    ports:
      - "{{ wg_port }}:51820/udp"
    volumes:
      - "{{ docker_dir }}/wg/:/etc/wireguard:z"
    restart_policy: unless-stopped
